### ISSUE TITLE
Create Wireframes for the 1st Draft.

### ISSUE THREAD

**Issue by MeepyMay** [systers/conference-android#1]
This should highlight the minimum needed for a conference:

1. Login - Facebook, Google
- User uses a previously made account or manually signs up with an email.
2. Registration - ID#/Code, Payment
- User can skip this screen or input a registration ID/code to continue.
- Do not detail this screen. Details come in the second draft. 
3. Viewing Sessions at the Conference - Details: date/time, speakers, location, and "track"
- User can view sessions by days and filter by tracks.
4. Adding sessions to your phone's calendar.
- Uses whatever default calendar the phone is set to, if not set then asks which calendar.
5. Viewing Floor Layouts 
- For the minimal viable product, we'll start with static floor layout images.
6. Include Profile Screen.
- Show what the profile would look like to connect more social media accounts, etc.

**Comment by MeepyMay** [comment]
Please use this color scheme:

Links = Orange, Headings = Blue/Green

Don't use red. (For now.)

![screen shot 2017-05-10 at 16 08 31](https://cloud.githubusercontent.com/assets/2440938/25920161/07edee90-359f-11e7-93cc-990255ef71df.png)

**Comment by abs51295** [comment]
test

**Comment by MeepyMay** [comment]
@abs51295 I've updated to include a profile screen. The "registration/payment" screen should only show an area to input a code or to "Skip" or right below the input box "Need to Register?"

Don't include any details about what happens after a code is inputted. We'll add that as we test with eReg data on etouches later okay?

**Comment by abs51295** [comment]
Yep got it @MeepyMay 👍

**Comment by MeepyMay** [comment]
Add Title and Company fields.
