### ISSUE TITLE
Mentors create issues for the first version of Conference Android.

### ISSUE THREAD

**Issue by MeepyMay** [systers/conference-android#13]
**Description**
As an Student, 
I want to view all the work I need to do, 
so that I can manage my time and program with weekly deployments on time.

**Mocks**
N/A

**Acceptance Criteria**
- Student can view all user stories in the issues list.
- User stories follow this format.
- Includes labels, assignees, and added to the "Student Tasks" Project board.

**Definition of Done**
- Matches all the user stories discussed in [CONF 1.0 Doc](https://docs.google.com/document/d/1Ldd-26wRQHEYDMdFfXBbXrFfwaFaDRD_b3VcT5QaOVA/edit?usp=sharing).

**Estimation**
- 1 Hour

**Comment by chhavip** [comment]
This has been completed as well but issues for some features left off the major ones will need to be created separately once the API is set up and there is some data. The features not included have been indicated in each PR/issue.
