### ISSUE TITLE
User will have a profile detail page with personal details

### ISSUE THREAD

**Issue by riddhik84** [systers/conference-android#18]
**Description**
As an attendee, 
I want to view my profile details like name, title, email, linked accounts.

**Mocks**
![image](https://cloud.githubusercontent.com/assets/1910385/26796323/aae8d66c-4a46-11e7-9bc6-dc7e655847af.png)

**Acceptance Criteria**
- User open profile detail screen.
- User can review information provided.
- User can edit profile detail page details.
- User can save the profile detail changes.

**Definition of Done**
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by UI team.
- Able to show feature in demo.

**Estimation**
- 3-4 Hours

**Comment by chhavip** [comment]
Closed via #30
