### ISSUE TITLE
Minor UI Issues

### ISSUE THREAD

**Issue by chhavip** [systers/conference-android#27]
Fix the following 

- Width of Fb Sign-In and Google Sign-in button differs at runtime.
- The text displayed on Fb Sign-In is "Continue with Facebook", should be changed to "Sign-In with Facebook"

**Comment by MeepyMay** [comment]
When data is not present in the First Name, Last Name fields, etc. Switch the underline from yellow to red (#EF4135).

**Comment by vaibhavsingh97** [comment]
@chhavip @MeepyMay Can I work on this issue or reserved for GSOC?

**Comment by chhavip** [comment]
@vaibhavsingh97 You can go ahead with this task
