### ISSUE TITLE
Update UI mock screens.

### ISSUE THREAD

**Issue by MeepyMay** [systers/conference-android#29]
## Description
As an Admin, 
I want to see a quick mock screen that reflects UI changes, 
so that I can relate the updates to other ABI staff and get approvals.

## Mocks
![screen shot 2017-05-11 at 16 20 05](https://cloud.githubusercontent.com/assets/2440938/25971135/3831a2ac-3669-11e7-9b91-0fd69b45719c.png)

## Acceptance Criteria
- All yellow switched to orange.
- Any error fields switched to an underline of red.

## Definition of Done
- Mocks commented on this issue.

## Estimation
- 1 Hour

**Comment by abs51295** [comment]
@MeepyMay here are the screenshots from the device after changing the colors as suggested:

![edit_profile](https://user-images.githubusercontent.com/13438222/27148055-97bdde08-515c-11e7-9a79-33978b274bdf.png)
![event_details](https://user-images.githubusercontent.com/13438222/27148057-97c0b2e0-515c-11e7-97e3-d41c4339d957.png)
![profile](https://user-images.githubusercontent.com/13438222/27148054-97bbd9aa-515c-11e7-88b1-4b9971cf9886.png)
![red_underline](https://user-images.githubusercontent.com/13438222/27148160-de1f0a20-515c-11e7-87e4-07676d87bd87.png)
![verify_details](https://user-images.githubusercontent.com/13438222/27148058-97ca791a-515c-11e7-9071-83515ff41f98.png)
![day_one](https://user-images.githubusercontent.com/13438222/27148060-97fafc02-515c-11e7-9ed3-113285abb194.png)
