### ISSUE TITLE
Implement Autocomplete on Company names in Profile Page

### ISSUE THREAD

**Issue by chhavip** [systers/conference-android#32]
## Description
As a User, 
I want to see auto complete suggestions when filling in Company name in profile page

## Acceptance Criteria
- An API being used to fetch auto complete suggestions for company names
- Name of company being updated once user clicks on it.

## Definition of Done
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by UI team.
- Able to show feature in demo.

## Estimation
- 2 Hour

**Comment by vaibhavsingh97** [comment]
@chhavip can i work on this issue?

**Comment by vaibhavsingh97** [comment]
@abs51295 I can work on this issue. Is anything you want me to take care off?
@chhavip Please assign this issue to me

**Comment by m-murad** [comment]
This cannot be done till we have a backend for this. Closing this for now.
