### ISSUE TITLE
Incorrect screen on pressing back button from edit profile screen

### ISSUE THREAD

**Issue by riddhik84** [systers/conference-android#35]
**Description**
As an attendee, 
When I press back or save button from edit profile screen,
user profile screen should appear

**Mocks**
-

**Acceptance Criteria**
- On pressing back button from edit profile screen, profile screen should appear
- On pressing save button from edit profile screen, profile screen should appear

**Definition of Done**
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by UI team.
- Able to show feature in demo.

**Estimation**
- 1 Hour

**Comment by chhavip** [comment]
Fixed via #36
