### ISSUE TITLE
User logs into app with Facebook.

### ISSUE THREAD

**Issue by MeepyMay** [systers/conference-android#4]
**Description**
_[TEMPLATE] As a (USER), I want to (DO THIS), so that I can (ACHIEVE THAT)._
As an attendee, 
I want to login with Facebook, 
so that I can include my information to register for the event.

**Mocks**
![screen shot 2017-05-22 at 11 44 26](https://cloud.githubusercontent.com/assets/2440938/26321062/5abfba24-3ef3-11e7-823c-ef55168dfcc2.png)

**Acceptance Criteria**
- User logins to Facebook.
- User can review information provided.
- User receives success/failure integration message.

**Definition of Done**
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Approved by UI team.
- Able to show feature in demo.

**Estimation**
- 2 Hours

**Comment by chhavip** [comment]
Closed via #10
