### ISSUE TITLE
User Registers for the Event - using Firebase

### ISSUE THREAD

**Issue by chhavip** [systers/conference-android#6]
**Description**
As an attendee, 
I want to register for the event
so that I can obtain information about the event 

**Acceptance Criteria**
- User information is relayed to the server via Etouches API
- User can review information provided.
- User receives success/failure integration message.

**Definition of Done**
- Passes all regression tests.
- Passes testing per acceptance criteria items.
- Information is parsed and successfully stored at the server

**Estimation**
- 4 - 5 Hours

**Comment by abs51295** [comment]
@chhavip This is already done. Can we close this issue?
