### ISSUE TITLE
Add Bottom App Bar  (Material design component)

### ISSUE THREAD

**Issue by roopalJazz** [systers/conference-android#82]
## Description
As a user, I need to able to navigate through the app easily,
I need a bottom app bar,
so that I have access to a bottom navigation drawer and actions related to the current screen.

## Mocks
![image](https://user-images.githubusercontent.com/19304435/41816977-a726cb46-77af-11e8-83cb-5930c0b43177.png)

### Update [Required]
- [ ] Bottom App bar

## Definition of Done
- [ ] All of the required items are completed.
- [ ] Approval by 1 mentor.

## Estimation
2 hours

**Comment by abs51295** [comment]
@roopalJazz @haroonshah2764 @ExactlyMay can anyone provide me a good example of any popular application using this? I personally think that the current design is much more aligned to what users are actually using, but there can be applications which I might be missing. Thanks.
